spring.application.name=carrentalsystem


spring.data.mongodb.uri = mongodb://localhost:27017/CarRentalSystem

aws.access.key = AKIA34AMDH5RXQIRV4XL
aws.secret.key = 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
aws.region = ap-south-1
aws.s3.carsbucket=cars-rental-system
aws.s3.dlbucket=car-rental-system-client-dl-bucket
aws.s3.dpbucket=car-rental-system-customer