spring.application.name=carrentalsystem


spring.data.mongodb.uri = mongodb://localhost:27017/CarRentalSystem

aws.access.key = AKIA34AMDH5RXQIRV4XL
aws.secret.key = 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
aws.region = ap-south-1
aws.s3.carsbucket=cars-rental-system
aws.s3.dlbucket=car-rental-system-client-dl-bucket
aws.s3.dpbucket=car-rental-system-customer


# --- GMAIL SMTP CONFIGURATION ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hacker.withuae@gmail.com
spring.mail.password=jipt rmep kakj qzoz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# --- TWILIO CONFIGURATION ---
twilio.account_sid=AC0311a60a13188e31606b0a8af37d456e
twilio.auth_token=a1b081ef6e6a82f419b9f4510004236a
twilio.phone_number=+16065432518